package com.xinwis.pms.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class Bi_buildingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public Bi_buildingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBuildUnitIsNull() {
            addCriterion("BUILD_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andBuildUnitIsNotNull() {
            addCriterion("BUILD_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andBuildUnitEqualTo(String value) {
            addCriterion("BUILD_UNIT =", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitNotEqualTo(String value) {
            addCriterion("BUILD_UNIT <>", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitGreaterThan(String value) {
            addCriterion("BUILD_UNIT >", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitGreaterThanOrEqualTo(String value) {
            addCriterion("BUILD_UNIT >=", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitLessThan(String value) {
            addCriterion("BUILD_UNIT <", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitLessThanOrEqualTo(String value) {
            addCriterion("BUILD_UNIT <=", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitLike(String value) {
            addCriterion("BUILD_UNIT like", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitNotLike(String value) {
            addCriterion("BUILD_UNIT not like", value, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitIn(List<String> values) {
            addCriterion("BUILD_UNIT in", values, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitNotIn(List<String> values) {
            addCriterion("BUILD_UNIT not in", values, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitBetween(String value1, String value2) {
            addCriterion("BUILD_UNIT between", value1, value2, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andBuildUnitNotBetween(String value1, String value2) {
            addCriterion("BUILD_UNIT not between", value1, value2, "buildUnit");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameIsNull() {
            addCriterion("GENERALIZE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameIsNotNull() {
            addCriterion("GENERALIZE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameEqualTo(String value) {
            addCriterion("GENERALIZE_NAME =", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameNotEqualTo(String value) {
            addCriterion("GENERALIZE_NAME <>", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameGreaterThan(String value) {
            addCriterion("GENERALIZE_NAME >", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameGreaterThanOrEqualTo(String value) {
            addCriterion("GENERALIZE_NAME >=", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameLessThan(String value) {
            addCriterion("GENERALIZE_NAME <", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameLessThanOrEqualTo(String value) {
            addCriterion("GENERALIZE_NAME <=", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameLike(String value) {
            addCriterion("GENERALIZE_NAME like", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameNotLike(String value) {
            addCriterion("GENERALIZE_NAME not like", value, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameIn(List<String> values) {
            addCriterion("GENERALIZE_NAME in", values, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameNotIn(List<String> values) {
            addCriterion("GENERALIZE_NAME not in", values, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameBetween(String value1, String value2) {
            addCriterion("GENERALIZE_NAME between", value1, value2, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameNotBetween(String value1, String value2) {
            addCriterion("GENERALIZE_NAME not between", value1, value2, "generalizeName");
            return (Criteria) this;
        }

        public Criteria andApplicationIsNull() {
            addCriterion("APPLICATION is null");
            return (Criteria) this;
        }

        public Criteria andApplicationIsNotNull() {
            addCriterion("APPLICATION is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationEqualTo(String value) {
            addCriterion("APPLICATION =", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotEqualTo(String value) {
            addCriterion("APPLICATION <>", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationGreaterThan(String value) {
            addCriterion("APPLICATION >", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationGreaterThanOrEqualTo(String value) {
            addCriterion("APPLICATION >=", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLessThan(String value) {
            addCriterion("APPLICATION <", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLessThanOrEqualTo(String value) {
            addCriterion("APPLICATION <=", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLike(String value) {
            addCriterion("APPLICATION like", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotLike(String value) {
            addCriterion("APPLICATION not like", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationIn(List<String> values) {
            addCriterion("APPLICATION in", values, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotIn(List<String> values) {
            addCriterion("APPLICATION not in", values, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationBetween(String value1, String value2) {
            addCriterion("APPLICATION between", value1, value2, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotBetween(String value1, String value2) {
            addCriterion("APPLICATION not between", value1, value2, "application");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesIsNull() {
            addCriterion("COMMERCIAL_ACTIVITIES is null");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesIsNotNull() {
            addCriterion("COMMERCIAL_ACTIVITIES is not null");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesEqualTo(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES =", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesNotEqualTo(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES <>", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesGreaterThan(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES >", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesGreaterThanOrEqualTo(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES >=", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesLessThan(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES <", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesLessThanOrEqualTo(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES <=", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesLike(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES like", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesNotLike(String value) {
            addCriterion("COMMERCIAL_ACTIVITIES not like", value, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesIn(List<String> values) {
            addCriterion("COMMERCIAL_ACTIVITIES in", values, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesNotIn(List<String> values) {
            addCriterion("COMMERCIAL_ACTIVITIES not in", values, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesBetween(String value1, String value2) {
            addCriterion("COMMERCIAL_ACTIVITIES between", value1, value2, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesNotBetween(String value1, String value2) {
            addCriterion("COMMERCIAL_ACTIVITIES not between", value1, value2, "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceIsNull() {
            addCriterion("BUILD_SPACE is null");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceIsNotNull() {
            addCriterion("BUILD_SPACE is not null");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceEqualTo(BigDecimal value) {
            addCriterion("BUILD_SPACE =", value, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceNotEqualTo(BigDecimal value) {
            addCriterion("BUILD_SPACE <>", value, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceGreaterThan(BigDecimal value) {
            addCriterion("BUILD_SPACE >", value, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BUILD_SPACE >=", value, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceLessThan(BigDecimal value) {
            addCriterion("BUILD_SPACE <", value, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BUILD_SPACE <=", value, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceIn(List<BigDecimal> values) {
            addCriterion("BUILD_SPACE in", values, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceNotIn(List<BigDecimal> values) {
            addCriterion("BUILD_SPACE not in", values, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUILD_SPACE between", value1, value2, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andBuildSpaceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUILD_SPACE not between", value1, value2, "buildSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceIsNull() {
            addCriterion("SULT_SPACE is null");
            return (Criteria) this;
        }

        public Criteria andSultSpaceIsNotNull() {
            addCriterion("SULT_SPACE is not null");
            return (Criteria) this;
        }

        public Criteria andSultSpaceEqualTo(BigDecimal value) {
            addCriterion("SULT_SPACE =", value, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceNotEqualTo(BigDecimal value) {
            addCriterion("SULT_SPACE <>", value, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceGreaterThan(BigDecimal value) {
            addCriterion("SULT_SPACE >", value, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SULT_SPACE >=", value, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceLessThan(BigDecimal value) {
            addCriterion("SULT_SPACE <", value, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SULT_SPACE <=", value, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceIn(List<BigDecimal> values) {
            addCriterion("SULT_SPACE in", values, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceNotIn(List<BigDecimal> values) {
            addCriterion("SULT_SPACE not in", values, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SULT_SPACE between", value1, value2, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSultSpaceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SULT_SPACE not between", value1, value2, "sultSpace");
            return (Criteria) this;
        }

        public Criteria andSeatTotalIsNull() {
            addCriterion("SEAT_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andSeatTotalIsNotNull() {
            addCriterion("SEAT_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andSeatTotalEqualTo(BigDecimal value) {
            addCriterion("SEAT_TOTAL =", value, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalNotEqualTo(BigDecimal value) {
            addCriterion("SEAT_TOTAL <>", value, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalGreaterThan(BigDecimal value) {
            addCriterion("SEAT_TOTAL >", value, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SEAT_TOTAL >=", value, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalLessThan(BigDecimal value) {
            addCriterion("SEAT_TOTAL <", value, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SEAT_TOTAL <=", value, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalIn(List<BigDecimal> values) {
            addCriterion("SEAT_TOTAL in", values, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalNotIn(List<BigDecimal> values) {
            addCriterion("SEAT_TOTAL not in", values, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEAT_TOTAL between", value1, value2, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andSeatTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SEAT_TOTAL not between", value1, value2, "seatTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalIsNull() {
            addCriterion("FLOOR_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andFloorTotalIsNotNull() {
            addCriterion("FLOOR_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andFloorTotalEqualTo(BigDecimal value) {
            addCriterion("FLOOR_TOTAL =", value, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalNotEqualTo(BigDecimal value) {
            addCriterion("FLOOR_TOTAL <>", value, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalGreaterThan(BigDecimal value) {
            addCriterion("FLOOR_TOTAL >", value, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOOR_TOTAL >=", value, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalLessThan(BigDecimal value) {
            addCriterion("FLOOR_TOTAL <", value, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOOR_TOTAL <=", value, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalIn(List<BigDecimal> values) {
            addCriterion("FLOOR_TOTAL in", values, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalNotIn(List<BigDecimal> values) {
            addCriterion("FLOOR_TOTAL not in", values, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOOR_TOTAL between", value1, value2, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andFloorTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOOR_TOTAL not between", value1, value2, "floorTotal");
            return (Criteria) this;
        }

        public Criteria andBuildHeightIsNull() {
            addCriterion("BUILD_HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andBuildHeightIsNotNull() {
            addCriterion("BUILD_HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andBuildHeightEqualTo(BigDecimal value) {
            addCriterion("BUILD_HEIGHT =", value, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightNotEqualTo(BigDecimal value) {
            addCriterion("BUILD_HEIGHT <>", value, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightGreaterThan(BigDecimal value) {
            addCriterion("BUILD_HEIGHT >", value, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BUILD_HEIGHT >=", value, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightLessThan(BigDecimal value) {
            addCriterion("BUILD_HEIGHT <", value, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BUILD_HEIGHT <=", value, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightIn(List<BigDecimal> values) {
            addCriterion("BUILD_HEIGHT in", values, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightNotIn(List<BigDecimal> values) {
            addCriterion("BUILD_HEIGHT not in", values, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUILD_HEIGHT between", value1, value2, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andBuildHeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUILD_HEIGHT not between", value1, value2, "buildHeight");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalIsNull() {
            addCriterion("PROPERTY_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalIsNotNull() {
            addCriterion("PROPERTY_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalEqualTo(BigDecimal value) {
            addCriterion("PROPERTY_TOTAL =", value, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalNotEqualTo(BigDecimal value) {
            addCriterion("PROPERTY_TOTAL <>", value, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalGreaterThan(BigDecimal value) {
            addCriterion("PROPERTY_TOTAL >", value, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PROPERTY_TOTAL >=", value, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalLessThan(BigDecimal value) {
            addCriterion("PROPERTY_TOTAL <", value, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PROPERTY_TOTAL <=", value, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalIn(List<BigDecimal> values) {
            addCriterion("PROPERTY_TOTAL in", values, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalNotIn(List<BigDecimal> values) {
            addCriterion("PROPERTY_TOTAL not in", values, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROPERTY_TOTAL between", value1, value2, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andPropertyTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROPERTY_TOTAL not between", value1, value2, "propertyTotal");
            return (Criteria) this;
        }

        public Criteria andCompletedDateIsNull() {
            addCriterion("COMPLETED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCompletedDateIsNotNull() {
            addCriterion("COMPLETED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCompletedDateEqualTo(Date value) {
            addCriterion("COMPLETED_DATE =", value, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateNotEqualTo(Date value) {
            addCriterion("COMPLETED_DATE <>", value, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateGreaterThan(Date value) {
            addCriterion("COMPLETED_DATE >", value, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("COMPLETED_DATE >=", value, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateLessThan(Date value) {
            addCriterion("COMPLETED_DATE <", value, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateLessThanOrEqualTo(Date value) {
            addCriterion("COMPLETED_DATE <=", value, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateIn(List<Date> values) {
            addCriterion("COMPLETED_DATE in", values, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateNotIn(List<Date> values) {
            addCriterion("COMPLETED_DATE not in", values, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateBetween(Date value1, Date value2) {
            addCriterion("COMPLETED_DATE between", value1, value2, "completedDate");
            return (Criteria) this;
        }

        public Criteria andCompletedDateNotBetween(Date value1, Date value2) {
            addCriterion("COMPLETED_DATE not between", value1, value2, "completedDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateIsNull() {
            addCriterion("REPOSSESSION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateIsNotNull() {
            addCriterion("REPOSSESSION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateEqualTo(Date value) {
            addCriterion("REPOSSESSION_DATE =", value, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateNotEqualTo(Date value) {
            addCriterion("REPOSSESSION_DATE <>", value, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateGreaterThan(Date value) {
            addCriterion("REPOSSESSION_DATE >", value, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateGreaterThanOrEqualTo(Date value) {
            addCriterion("REPOSSESSION_DATE >=", value, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateLessThan(Date value) {
            addCriterion("REPOSSESSION_DATE <", value, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateLessThanOrEqualTo(Date value) {
            addCriterion("REPOSSESSION_DATE <=", value, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateIn(List<Date> values) {
            addCriterion("REPOSSESSION_DATE in", values, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateNotIn(List<Date> values) {
            addCriterion("REPOSSESSION_DATE not in", values, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateBetween(Date value1, Date value2) {
            addCriterion("REPOSSESSION_DATE between", value1, value2, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andRepossessionDateNotBetween(Date value1, Date value2) {
            addCriterion("REPOSSESSION_DATE not between", value1, value2, "repossessionDate");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusIsNull() {
            addCriterion("SPRUCE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusIsNotNull() {
            addCriterion("SPRUCE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusEqualTo(BigDecimal value) {
            addCriterion("SPRUCE_STATUS =", value, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusNotEqualTo(BigDecimal value) {
            addCriterion("SPRUCE_STATUS <>", value, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusGreaterThan(BigDecimal value) {
            addCriterion("SPRUCE_STATUS >", value, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SPRUCE_STATUS >=", value, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusLessThan(BigDecimal value) {
            addCriterion("SPRUCE_STATUS <", value, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SPRUCE_STATUS <=", value, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusIn(List<BigDecimal> values) {
            addCriterion("SPRUCE_STATUS in", values, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusNotIn(List<BigDecimal> values) {
            addCriterion("SPRUCE_STATUS not in", values, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SPRUCE_STATUS between", value1, value2, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andSpruceStatusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SPRUCE_STATUS not between", value1, value2, "spruceStatus");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitIsNull() {
            addCriterion("CONSTRUT_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitIsNotNull() {
            addCriterion("CONSTRUT_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitEqualTo(String value) {
            addCriterion("CONSTRUT_UNIT =", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitNotEqualTo(String value) {
            addCriterion("CONSTRUT_UNIT <>", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitGreaterThan(String value) {
            addCriterion("CONSTRUT_UNIT >", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRUT_UNIT >=", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitLessThan(String value) {
            addCriterion("CONSTRUT_UNIT <", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitLessThanOrEqualTo(String value) {
            addCriterion("CONSTRUT_UNIT <=", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitLike(String value) {
            addCriterion("CONSTRUT_UNIT like", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitNotLike(String value) {
            addCriterion("CONSTRUT_UNIT not like", value, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitIn(List<String> values) {
            addCriterion("CONSTRUT_UNIT in", values, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitNotIn(List<String> values) {
            addCriterion("CONSTRUT_UNIT not in", values, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitBetween(String value1, String value2) {
            addCriterion("CONSTRUT_UNIT between", value1, value2, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitNotBetween(String value1, String value2) {
            addCriterion("CONSTRUT_UNIT not between", value1, value2, "construtUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitIsNull() {
            addCriterion("SUPERVISOR_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitIsNotNull() {
            addCriterion("SUPERVISOR_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitEqualTo(String value) {
            addCriterion("SUPERVISOR_UNIT =", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitNotEqualTo(String value) {
            addCriterion("SUPERVISOR_UNIT <>", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitGreaterThan(String value) {
            addCriterion("SUPERVISOR_UNIT >", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitGreaterThanOrEqualTo(String value) {
            addCriterion("SUPERVISOR_UNIT >=", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitLessThan(String value) {
            addCriterion("SUPERVISOR_UNIT <", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitLessThanOrEqualTo(String value) {
            addCriterion("SUPERVISOR_UNIT <=", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitLike(String value) {
            addCriterion("SUPERVISOR_UNIT like", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitNotLike(String value) {
            addCriterion("SUPERVISOR_UNIT not like", value, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitIn(List<String> values) {
            addCriterion("SUPERVISOR_UNIT in", values, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitNotIn(List<String> values) {
            addCriterion("SUPERVISOR_UNIT not in", values, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitBetween(String value1, String value2) {
            addCriterion("SUPERVISOR_UNIT between", value1, value2, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitNotBetween(String value1, String value2) {
            addCriterion("SUPERVISOR_UNIT not between", value1, value2, "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andInRateIsNull() {
            addCriterion("IN_RATE is null");
            return (Criteria) this;
        }

        public Criteria andInRateIsNotNull() {
            addCriterion("IN_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andInRateEqualTo(String value) {
            addCriterion("IN_RATE =", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateNotEqualTo(String value) {
            addCriterion("IN_RATE <>", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateGreaterThan(String value) {
            addCriterion("IN_RATE >", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateGreaterThanOrEqualTo(String value) {
            addCriterion("IN_RATE >=", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateLessThan(String value) {
            addCriterion("IN_RATE <", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateLessThanOrEqualTo(String value) {
            addCriterion("IN_RATE <=", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateLike(String value) {
            addCriterion("IN_RATE like", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateNotLike(String value) {
            addCriterion("IN_RATE not like", value, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateIn(List<String> values) {
            addCriterion("IN_RATE in", values, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateNotIn(List<String> values) {
            addCriterion("IN_RATE not in", values, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateBetween(String value1, String value2) {
            addCriterion("IN_RATE between", value1, value2, "inRate");
            return (Criteria) this;
        }

        public Criteria andInRateNotBetween(String value1, String value2) {
            addCriterion("IN_RATE not between", value1, value2, "inRate");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardIsNull() {
            addCriterion("PROPERTY_FEE_STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardIsNotNull() {
            addCriterion("PROPERTY_FEE_STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardEqualTo(String value) {
            addCriterion("PROPERTY_FEE_STANDARD =", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardNotEqualTo(String value) {
            addCriterion("PROPERTY_FEE_STANDARD <>", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardGreaterThan(String value) {
            addCriterion("PROPERTY_FEE_STANDARD >", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTY_FEE_STANDARD >=", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardLessThan(String value) {
            addCriterion("PROPERTY_FEE_STANDARD <", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardLessThanOrEqualTo(String value) {
            addCriterion("PROPERTY_FEE_STANDARD <=", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardLike(String value) {
            addCriterion("PROPERTY_FEE_STANDARD like", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardNotLike(String value) {
            addCriterion("PROPERTY_FEE_STANDARD not like", value, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardIn(List<String> values) {
            addCriterion("PROPERTY_FEE_STANDARD in", values, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardNotIn(List<String> values) {
            addCriterion("PROPERTY_FEE_STANDARD not in", values, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardBetween(String value1, String value2) {
            addCriterion("PROPERTY_FEE_STANDARD between", value1, value2, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardNotBetween(String value1, String value2) {
            addCriterion("PROPERTY_FEE_STANDARD not between", value1, value2, "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andLiftFirmIsNull() {
            addCriterion("LIFT_FIRM is null");
            return (Criteria) this;
        }

        public Criteria andLiftFirmIsNotNull() {
            addCriterion("LIFT_FIRM is not null");
            return (Criteria) this;
        }

        public Criteria andLiftFirmEqualTo(String value) {
            addCriterion("LIFT_FIRM =", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmNotEqualTo(String value) {
            addCriterion("LIFT_FIRM <>", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmGreaterThan(String value) {
            addCriterion("LIFT_FIRM >", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmGreaterThanOrEqualTo(String value) {
            addCriterion("LIFT_FIRM >=", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmLessThan(String value) {
            addCriterion("LIFT_FIRM <", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmLessThanOrEqualTo(String value) {
            addCriterion("LIFT_FIRM <=", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmLike(String value) {
            addCriterion("LIFT_FIRM like", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmNotLike(String value) {
            addCriterion("LIFT_FIRM not like", value, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmIn(List<String> values) {
            addCriterion("LIFT_FIRM in", values, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmNotIn(List<String> values) {
            addCriterion("LIFT_FIRM not in", values, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmBetween(String value1, String value2) {
            addCriterion("LIFT_FIRM between", value1, value2, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andLiftFirmNotBetween(String value1, String value2) {
            addCriterion("LIFT_FIRM not between", value1, value2, "liftFirm");
            return (Criteria) this;
        }

        public Criteria andMortgateBankIsNull() {
            addCriterion("MORTGATE_BANK is null");
            return (Criteria) this;
        }

        public Criteria andMortgateBankIsNotNull() {
            addCriterion("MORTGATE_BANK is not null");
            return (Criteria) this;
        }

        public Criteria andMortgateBankEqualTo(String value) {
            addCriterion("MORTGATE_BANK =", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankNotEqualTo(String value) {
            addCriterion("MORTGATE_BANK <>", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankGreaterThan(String value) {
            addCriterion("MORTGATE_BANK >", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankGreaterThanOrEqualTo(String value) {
            addCriterion("MORTGATE_BANK >=", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankLessThan(String value) {
            addCriterion("MORTGATE_BANK <", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankLessThanOrEqualTo(String value) {
            addCriterion("MORTGATE_BANK <=", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankLike(String value) {
            addCriterion("MORTGATE_BANK like", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankNotLike(String value) {
            addCriterion("MORTGATE_BANK not like", value, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankIn(List<String> values) {
            addCriterion("MORTGATE_BANK in", values, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankNotIn(List<String> values) {
            addCriterion("MORTGATE_BANK not in", values, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankBetween(String value1, String value2) {
            addCriterion("MORTGATE_BANK between", value1, value2, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andMortgateBankNotBetween(String value1, String value2) {
            addCriterion("MORTGATE_BANK not between", value1, value2, "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("DEL is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("DEL is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(BigDecimal value) {
            addCriterion("DEL =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(BigDecimal value) {
            addCriterion("DEL <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(BigDecimal value) {
            addCriterion("DEL >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DEL >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(BigDecimal value) {
            addCriterion("DEL <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DEL <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<BigDecimal> values) {
            addCriterion("DEL in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<BigDecimal> values) {
            addCriterion("DEL not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DEL between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DEL not between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andAttaIdIsNull() {
            addCriterion("ATTA_ID is null");
            return (Criteria) this;
        }

        public Criteria andAttaIdIsNotNull() {
            addCriterion("ATTA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAttaIdEqualTo(String value) {
            addCriterion("ATTA_ID =", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdNotEqualTo(String value) {
            addCriterion("ATTA_ID <>", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdGreaterThan(String value) {
            addCriterion("ATTA_ID >", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdGreaterThanOrEqualTo(String value) {
            addCriterion("ATTA_ID >=", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdLessThan(String value) {
            addCriterion("ATTA_ID <", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdLessThanOrEqualTo(String value) {
            addCriterion("ATTA_ID <=", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdLike(String value) {
            addCriterion("ATTA_ID like", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdNotLike(String value) {
            addCriterion("ATTA_ID not like", value, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdIn(List<String> values) {
            addCriterion("ATTA_ID in", values, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdNotIn(List<String> values) {
            addCriterion("ATTA_ID not in", values, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdBetween(String value1, String value2) {
            addCriterion("ATTA_ID between", value1, value2, "attaId");
            return (Criteria) this;
        }

        public Criteria andAttaIdNotBetween(String value1, String value2) {
            addCriterion("ATTA_ID not between", value1, value2, "attaId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("CREATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("CREATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(BigDecimal value) {
            addCriterion("CREATE_ID =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(BigDecimal value) {
            addCriterion("CREATE_ID <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(BigDecimal value) {
            addCriterion("CREATE_ID >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_ID >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(BigDecimal value) {
            addCriterion("CREATE_ID <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_ID <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<BigDecimal> values) {
            addCriterion("CREATE_ID in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<BigDecimal> values) {
            addCriterion("CREATE_ID not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_ID between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_ID not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(BigDecimal value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(BigDecimal value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(BigDecimal value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(BigDecimal value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<BigDecimal> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<BigDecimal> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(CODE) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(NAME) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andBuildUnitLikeInsensitive(String value) {
            addCriterion("upper(BUILD_UNIT) like", value.toUpperCase(), "buildUnit");
            return (Criteria) this;
        }

        public Criteria andGeneralizeNameLikeInsensitive(String value) {
            addCriterion("upper(GENERALIZE_NAME) like", value.toUpperCase(), "generalizeName");
            return (Criteria) this;
        }

        public Criteria andApplicationLikeInsensitive(String value) {
            addCriterion("upper(APPLICATION) like", value.toUpperCase(), "application");
            return (Criteria) this;
        }

        public Criteria andCommercialActivitiesLikeInsensitive(String value) {
            addCriterion("upper(COMMERCIAL_ACTIVITIES) like", value.toUpperCase(), "commercialActivities");
            return (Criteria) this;
        }

        public Criteria andConstrutUnitLikeInsensitive(String value) {
            addCriterion("upper(CONSTRUT_UNIT) like", value.toUpperCase(), "construtUnit");
            return (Criteria) this;
        }

        public Criteria andSupervisorUnitLikeInsensitive(String value) {
            addCriterion("upper(SUPERVISOR_UNIT) like", value.toUpperCase(), "supervisorUnit");
            return (Criteria) this;
        }

        public Criteria andInRateLikeInsensitive(String value) {
            addCriterion("upper(IN_RATE) like", value.toUpperCase(), "inRate");
            return (Criteria) this;
        }

        public Criteria andPropertyFeeStandardLikeInsensitive(String value) {
            addCriterion("upper(PROPERTY_FEE_STANDARD) like", value.toUpperCase(), "propertyFeeStandard");
            return (Criteria) this;
        }

        public Criteria andLiftFirmLikeInsensitive(String value) {
            addCriterion("upper(LIFT_FIRM) like", value.toUpperCase(), "liftFirm");
            return (Criteria) this;
        }

        public Criteria andMortgateBankLikeInsensitive(String value) {
            addCriterion("upper(MORTGATE_BANK) like", value.toUpperCase(), "mortgateBank");
            return (Criteria) this;
        }

        public Criteria andAttaIdLikeInsensitive(String value) {
            addCriterion("upper(ATTA_ID) like", value.toUpperCase(), "attaId");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(REMARK) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BI_BUILDING
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BI_BUILDING
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}